version: '3'
services:

  # nginx
  nginx:
    image: bondagency/nginx-extras:latest
    expose:
      - 80
    volumes:
      - www-data:/var/www/html
      - www-cache:/var/www/cache
      - ./nginx/config/global:/etc/nginx/global:ro
      - ./nginx/config/h5bp:/etc/nginx/h5bp:ro
      - ./nginx/config/vhost.${NGINX_ENV}.conf:/etc/nginx/vhost.conf:ro
      - ./nginx/config/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wordpress/wp-content:/var/www/html/wp-content
    links:
      - wordpress
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - USER_ID=${USER_ID}

  # database
  database:
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
      - ./mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    environment:
      - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_PASSWORD}

  # wordpress
  wordpress:
    image: bondagency/docker-wpbp-wordpress
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
    links:
      - database
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/config/wp-config.php:/var/www/config/wp-config.php:ro
      - www-data:/var/www/html
      - www-cache:/var/www/cache
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_NAME=wordpress
      - WPTB_ENV=${WPTB_ENV}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - USER_ID=${USER_ID}

volumes:
  www-data:
  www-cache:

networks:
  default:
    external:
      name: nginx-proxy-network